using System.Text;
using System.Xml.Linq;

using Foundatio.CommandQuery.Queries;

#pragma warning disable IDE0130 // Namespace does not match folder structure
namespace Foundatio.CommandQuery;

/// <summary>
/// Provides functionality to build LINQ expression strings and parameter lists from <see cref="QueryFilter"/> objects.
/// Supports custom filter writers for extensibility and validation of query rules.
/// </summary>
public class LinqExpressionBuilder
{
    private static readonly Dictionary<QueryOperators, Action<StringBuilder, List<object?>, QueryFilter>> _filterWriters = [];

    /// <summary>
    /// Initializes static filter writers for supported query operators.
    /// </summary>
    static LinqExpressionBuilder()
    {
        _filterWriters.TryAdd(QueryOperators.Contains, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotContains, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.StartsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotStartsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.EndsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotEndsWith, WriteStringFilter);

        _filterWriters.TryAdd(QueryOperators.Equal, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.NotEqual, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.GreaterThan, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.GreaterThanOrEqual, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.LessThan, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.LessThanOrEqual, WriteStandardFilter);

        _filterWriters.TryAdd(QueryOperators.IsNull, WriteNullFilter);
        _filterWriters.TryAdd(QueryOperators.IsNotNull, WriteNullFilter);

        _filterWriters.TryAdd(QueryOperators.In, WriteInFilter);
        _filterWriters.TryAdd(QueryOperators.NotIn, WriteInFilter);

        _filterWriters.TryAdd(QueryOperators.Expression, WriteRawExpression);
    }


    /// <summary>
    /// Registers a custom filter writer for a specific query operator.
    /// </summary>
    /// <param name="operator">The query operator to register.</param>
    /// <param name="writer">The writer action to use for the operator.</param>
    public static void RegisterWriter(QueryOperators @operator, Action<StringBuilder, List<object?>, QueryFilter> writer)
    {
        _filterWriters[@operator] = writer;
    }

    private readonly StringBuilder _expression = new();
    private readonly List<object?> _values = [];

    /// <summary>
    /// Gets the list of parameters used in the built LINQ expression.  Generated by <see cref="Build(QueryFilter?)"/>.
    /// </summary>
    public IReadOnlyList<object?> Parameters => _values;

    /// <summary>
    /// Gets the LINQ expression string built from the query rule. Generated by <see cref="Build(QueryFilter?)"/>.
    /// </summary>
    public string Expression => _expression.ToString();

    /// <summary>
    /// Builds a LINQ expression string and parameter list from the specified <see cref="QueryFilter"/>.
    /// Expression will be updated with the generated LINQ expression.
    /// Parameters will also be updated with the values used in the expression.
    /// </summary>
    /// <param name="queryRule">The query rule to build the expression from.</param>
    public void Build(QueryFilter? queryRule)
    {
        _expression.Length = 0;
        _values.Clear();

        if (queryRule == null)
            return;

        Visit(queryRule);
    }

    /// <summary>
    /// Visits the specified <see cref="QueryFilter"/> and writes its expression.
    /// </summary>
    /// <param name="queryRule">The query rule to visit.</param>
    private void Visit(QueryFilter queryRule)
    {
        if (queryRule == null)
            return;

        if (queryRule.IsGroup())
            WriteGroup(queryRule);
        else if (queryRule is QueryFilter filter)
            WriteExpression(filter);
    }

    /// <summary>
    /// Writes a group expression for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="entityFilter">The query group to write.</param>
    private void WriteGroup(QueryFilter entityFilter)
    {
        var filters = entityFilter.Filters;

        if (filters == null || filters.Count == 0)
            return;

        var logic = entityFilter.Logic == QueryLogic.Or ? "||" : "&&";

        var wroteFirst = false;

        _expression.Append('(');
        foreach (var filter in filters)
        {
            if (wroteFirst)
                _expression.Append(' ').Append(logic).Append(' ');

            Visit(filter);
            wroteFirst = true;
        }
        _expression.Append(')');
    }

    /// <summary>
    /// Writes an expression for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="filter">The query filter to write.</param>
    private void WriteExpression(QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        // default comparison equal
        var comparison = filter.Operator ?? QueryOperators.Equal;

        if (_filterWriters.TryGetValue(comparison, out var action))
            action(_expression, _values, filter);
        else
            WriteStandardFilter(_expression, _values, filter);
    }


    /// <summary>
    /// Writes a string-based filter expression (e.g., Contains, StartsWith) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteStringFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        int index = parameters.Count;

        var field = filter.Name;
        var value = filter.Value;

        var method = filter.Operator switch
        {
            QueryOperators.StartsWith => "StartsWith",
            QueryOperators.NotStartsWith => "StartsWith",
            QueryOperators.EndsWith => "EndsWith",
            QueryOperators.NotEndsWith => "EndsWith",
            QueryOperators.Contains => "Contains",
            QueryOperators.NotContains => "Contains",
            _ => "Contains"
        };

        var negation = filter.Operator switch
        {
            QueryOperators.NotContains => true,
            QueryOperators.NotStartsWith => true,
            QueryOperators.NotEndsWith => true,
            _ => false
        };

        builder
            .Append(field)
            .Append(" != NULL && ");

        if (negation)
            builder.Append('!');

        builder
            .Append(field)
            .Append('.')
            .Append(method)
            .Append("(@")
            .Append(index)
            .Append(')');

        parameters.Add(value);
    }

    /// <summary>
    /// Writes a standard comparison filter expression (e.g., ==, !=, &gt;, &lt;) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteStandardFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        int index = parameters.Count;

        var field = filter.Name;
        var value = filter.Value;

        var comparison = filter.Operator switch
        {
            QueryOperators.Equal => "==",
            QueryOperators.NotEqual => "!=",
            QueryOperators.GreaterThan => ">",
            QueryOperators.GreaterThanOrEqual => ">=",
            QueryOperators.LessThan => "<",
            QueryOperators.LessThanOrEqual => "<=",
            _ => "=="
        };

        builder
            .Append(field)
            .Append(' ')
            .Append(comparison)
            .Append(" @")
            .Append(index);

        parameters.Add(value);
    }

    /// <summary>
    /// Writes a null-check filter expression (e.g., IsNull, IsNotNull) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteNullFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        int index = parameters.Count;

        var field = filter.Name;
        var value = filter.Value;

        var comparison = filter.Operator switch
        {
            QueryOperators.IsNull => "==",
            QueryOperators.IsNotNull => "!=",
            _ => "=="
        };

        builder
            .Append(field)
            .Append(' ')
            .Append(comparison)
            .Append(" NULL");
    }

    private static void WriteRawExpression(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        int index = parameters.Count;

        var field = filter.Name;
        var value = filter.Value;

        // fix up parameter index if used multiple times
        var expression = index == 0 ? field : field.Replace("@0", $"@{index}", StringComparison.OrdinalIgnoreCase);

        builder.Append(expression);

        parameters.Add(value);
    }

    private static void WriteInFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Name))
            return;

        int index = parameters.Count;

        var field = filter.Name;
        var value = filter.Value;

        var negation = filter.Operator == QueryOperators.NotIn;
        if (negation)
            builder.Append('!');

        builder
            .Append("it.")
            .Append(field)
            .Append(" in @")
            .Append(index);

        parameters.Add(value);
    }
}
